# Generated by Django 4.0.2 on 2022-05-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_products_alter_order_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
